### ISSUE TITLE
Pinging with discord id broken

### ISSUE THREAD

**Issue by toaster203** [ApocalypseCalculator/Someone#4]
When you ping by doing \@ Someone (without the space) the bot only pings itself
![image](https://user-images.githubusercontent.com/58535328/82738011-cc38ee80-9d02-11ea-9284-d9018d82bc4e.png)

**Comment by ApocalypseCalculator** [comment]
Fix live now, monitoring results.

**Comment by ApocalypseCalculator** [comment]
Fix seems to have no problems. Closed for now
