### ISSUE TITLE
Issue with @ everyone

### ISSUE THREAD

**Issue by ApocalypseCalculator** [ApocalypseCalculator/Someone#9]
Whenever @ everyone or @ here is used the bot will pop up with the "I'm going to give everyone 1 less ping by not repeating that with a Someone ping. tyvm" which is supposed to only be sent when the bot client is explicitly and pinged.

**Comment by l2zou** [comment]
Could you please clarify what the issue is? I could not reproduce anything on a local copy of the bot, or the bot itself.

![image](https://user-images.githubusercontent.com/25358260/95407428-fb837d00-08ea-11eb-9afe-ce467e7aa312.png)

**Comment by ApocalypseCalculator** [comment]
Seems like I've actually patched the issue during the refactor. Stupid me. Thanks anyways :)
